name: Deploy Lambda .NET 6

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do .NET 6
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      # Criar ambiente virtual para evitar conflitos de pacotes
      - name: Setup Python Virtual Environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install aws-sam-cli

      # Build do projeto com SAM
      - name: Build Lambda
        run: |
          source .venv/bin/activate
          sam build

      # Deploy do projeto com SAM
      - name: Deploy Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          source .venv/bin/activate
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
